n = 0
image_speed = 0.35
//sprite_index = spr_hud_pumpkin_piv
alarm[1] = 60
pivspr_index = 0
pivspr = spr_hud_pumpkin_piv
global.seconds = 59
global.minutes = 1
angle = 0
frame = 0
global.pizza = 0
global.pizzameter = 0
global.pillarhunger = 4000
basement = 0
shake_mag = 0
shake_mag_acc = 0
timestop = 1
zoom = 0
chargecamera = 0
alpha = 1
display_set_gui_size(960, 540)
global.panicbg = 1
global.maxwave = 0
global.wave = 0
font = font_add_sprite_ext(spr_font, "ABCDEFGHIJKLMNOPQRSTUVWXYZ!.1234567890:", 1, 0)
